stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - sqkj
  script:
    - cd /home/sqkj
    - git pull origin main
    - npm install
    - npm run build
    - pm2 reload sqkj
  environment:
    name: production
    url: http://sqkj.ru
  only:
    - main