deploy:
  stage: deploy
  tags:
    - sqkj
  script:
    - cd /home/sqkj
    - pm2 stop sqkj
    - rm -rf .next public
    - cp -r ../.next ./
    - cp -r ../public ./
    - npm install
    - pm2 start sqkj
  environment:
    name: production
    url: http://sqkj.ru
  only:
    - main